database:
  name: bloqly_rhea
  username: user_loge
  password: password_loge

port: 9902

admin:
  port: 9912
  username: rhea_admin
  password: rhea_password

nodes: localhost:9901,localhost:9903,localhost:9904

keys:
  passphrase_F7974E0C: "validator2 password"