database:
  name: bloqly_loge
  username: user_loge
  password: password_loge

port: 9903

admin:
  port: 9913
  username: loge_admin
  password: loge_password

nodes: localhost:9901,localhost:9902,localhost:9904

keys:
  passphrase_9CBDDA16: "validator3 password"