language: java

dist: trusty

services:
  - postgresql

addons:
  postgresql: "10"

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

before_script:
  - psql -c 'create database bloqly_test;' -U postgres
  
matrix:
  include:
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
      
script:
  - ./gradlew test
