language: java

sudo: false
dist: trusty

addons:
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  postgresql: 10

services:
  - postgresql

before_script:
  - psql -c 'create database bloqly_test;' -U postgres

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

  
matrix:
  include:
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
      
script:
  - ./gradlew test
