spring:
  profiles:
    active: production

  data:
    elasticsearch:
      repositories:
        enabled: false

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    pool-size: 30
    username: ${database.username}
    password: ${database.password}

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
