database:
  name: bloqly_ymir
  username: user_ymir
  password: password_ymir

port: 9904

admin:
  port: 9914
  username: ymir_admin
  password: ymir_password

nodes: localhost:9901,localhost:9902,localhost:9903

keys:
  passphrase_DA4A181C: "validator4 password"