database:
  name: bloqly_main
  username: user_main
  password: password_main

port: 9901

admin:
  port: 9911

nodes: localhost:9902,localhost:9903,localhost:9904

keys:
  passphrase_10CA5388: "validator1 password"